Table drives {
  drive_uuid integer [serial, primary key]
  drive_id_win integer [unique]
  drive_id_mac string [unique]
  drive_name string [not null]
}

Table files {
  file_uuid integer [serial, primary key]
  file_id_win integer [unique]
  file_id_mac integer [unique]
  drive_uuid string [not null]
  file_path string [not null]
}

Ref: drives.drive_uuid < files.drive_uuid

Table tags {
  tag_uuid integer [serial, primary key]
  file_id integer [not null]
  tag_name string [not null]
}

Ref: files.file_uuid < tags.file_id