Table drives {
  drive_uuid integer [primary key]
  drive_id_win dword [unique]
  drive_id_mac string [unique]
  drive_name string [not null]
}

Table files {
  file_id integer [primary key]
  file_id_win integer [unique]
  file_id_mac integer [unique]
  drive_id integer [not null]
  file_path string [not null]
}

Ref: drives.drive_uuid < files.drive_id

Table tags {
  file_id integer [primary key]
  tag_name string [not null]
}

Ref: files.file_id < tags.file_id